* Marketing Plan for DBS Roofing Systems Ghana Ltd. (2019 - 2024)

* Executive Summary
** Background
DBS which stands for Daniel Boateng and Sons was formed over 20 years ago in
Kumasi to provide roofing needs. They produce roofing sheets, roofing
accessories, steel trusses, shingle tiles and Eurotiles.

DBS has grown to understand the changing needs of its customers and has
positioned itself to consistently provide the changing needs of its custoers as
far as construction needs are concerned.

They have 5 main branches accross the country, which are situated in Accra,
Kumasi, Tamale, Takoradi and Sunyani.
** Objectives
*** Marketing Objectives
 - To establish ourselves as experts by the end of five years.
 - Increase our presence to other countries in the West African sub-region by
   the end of 2024.
 - Become a one-stop shop for construction materials before the by 2024.
*** Financial Objectives
 - Increase sales revenues by 30% - 40% each year for the next 5 years.
 - Reduction in cost of operations by 10% each year for the next 5 years.
** Strategy
** Proposed Financial Results
* Mission and Vision
** Mission statement
** Vision
** Core Values
DBS Systems Ghana Ltd. tries to incorporate the values of Quality, Affordability,
Excellence and Speed in all their activities. [Please expand on each point here].
* Situational Analysis
** Internal Analysis
**** Marketing Audit
***** Marketing Environment Audit 

[Summary Paragraph Goes here]

The main competitors are the companies that the prospective customers think
about as alternative when buying. The main one is Raincoat. Others are
Rocksters, Lion Aluminium, Alu Africa and K. K. Peprah. Raincoat has
distinguished itself in selling to institutions. It was startling to discover
that the marketing department did not have much to share on their competitor's
strategies. 

Currently, the target markets are individuals and institutions. The high
population growth rate of Ghana[how much?], coupled with a high housing deficit
[how much?] and economic growth[how much?] has led to an associated increase in
the  size of the target market projected growth. This presents both an
opportunity and a threat at the same time, which is discussed further in the
SWOT analysis.

The current estimated market share, according to the marketing manager is about
30%. They may therefore be classified as the market challenger, given that there
is no company with a bigger market share.

The target markets are further sub-divided by income/social class (High class,
mid class and low class) and geographic basis (Coastal area, mid section and the
north). In order to satisfy each sub-target properly, the company offers
different products. Eurotiles are targeted at the high class and also customers
that live near the coastal region. Their IDT and IDR products are aimed at
mid-income earners. All the other products are targeted at low-income earners.

Customers' needs, generally, is not stable in any industry. DBS is no
exception. The market's needs have changed over the years. Current trends include
the need for Eurotiles, which is a new product in the market to suit customers
who want to distinguish themselves. Self-locking roofing sheets which are
cheaper and easier to maintain than strip-lock sheets. Another current trend is
the use of aluzinc trusses to replace wooden trusses. DBS provides all of these
products to meet the changing needs of customers.

The company provides a seemingly unsatisfactory credit policy to customers. All
customers, aside from churches are required to make a down payment of 70% with
the rest to be settled within 2 months. Churches are allowed to make a down payment
of 50% with the rest to be settled within 3 months. However, given that in the
cultural context of the country in which it operates, most transactions are done
in cash, it does not seem to be too bad. Aside from this, there were no clear
outward signs of anything that might lead to a bad public perception towards the
company.

The company has 3 main suppliers. They are all exclusive suppliers who sell to
only the company and not to any of its competitors. The company also imports raw
materials. This leaves it vulnerable to the problems of foreign exchange rate
fluctuations. The current strategy is to pass on losses in foreign exchange to
the customers, which is hardly ideal.

Changes in government only affects them when the change in government affects
the general macro-economic enviroment of the country. While this is true for
them, the same could not be said about all their competitors. Some of their
competitors are owned by politicians and a change in government may lead to a
change in profitability and ability to compete. However, their main competitor,
Raincoat is affected in similar ways by a change of government as it does them.
***** Marketing Strategy Audit

[Summary Paragraph Goes here]

The unique benefits that the company tries to deliver to customers include the
following.
 - Durable products. DBS has positioned itself as a leader in the production of
   durable products. As evidence of the durability of their products, they offer
   100 years warranty on their steel trusses and 20 years warranty on their roofing
   sheets.
 - Exclusive lines. They provide some specific products just to suit the unique
   needs of high income earners and customers with a need for a level of
   prestige. To this end, they provide Eurotiles and Shingle Tiles which are new
   products on the market.
 - Services such as delivery, fixing and maintenance checks are provided by
   customers who need them.

The current competitive areas on which the company focuses include the
following. 
 - Widespread distribution. The company has manufacturing facilities in 5
   regions in Ghana. It owns all its warehouses and maintains its distribution
   network itself. The network is extensive enough to cover most of the major
   cities in Ghana and also reach other parts of the country. This provides
   certain advantages such as reduced cost and control over the quality of
   products throughout the whole distribution process.
 - Varied design. All the roofing sheets come in different forms and colors that
   is aimed at appealing to every customer.
 - Varied product phase???????
***** Marketing Organization Audit

 [ Summary paragraph goes here]

 [ Organisational diagram goes here]

 [ A brief description of the marketing department goes here]

 [ Highlight the problem between marketing and other departments here]

***** Marketing Systems Audit
***** Marketing Productivity Audit

[Summary paragraph goes here]

The company spends approximately 7% of all sales revenue on advertisement. This,
according to the marketing manager, does not seem to be too excessive given the
amount of growth in sales that has been recorded historically due to
advertisement [Please provide some citation!!!]

Should the company enter, expand, contract or withdraw from any business
segments, and what would be the short and long-run profit consequences?

***** Marketing Function Audit
**** Financial Resources
**** Human Resources
**** Technological Appraisal
** External Analysis
*** Customers
*** Competitors
*** Industrial Analysis
*** Distribution analysis
*** Threat of new entrants
*** Threat of substitutes
*** Government and regulatory body activities
**** Current actions
**** Potential actions
* SWOT Analysis
** The Grid
** Analysis of the Grid
* Critical Issues
[Further detailed analysis of the findings in the SWOT grid and strategies the
company can use to  best deal with them.]
* Key Success Factors
** Industry analysis
*** Find out what the bigger players are doing right
** Internal strategies
**** What is the current strategy employed by the company?
** Customer views
*** What do the customers really want?
* Market Definition
** Segmentation
** Targeting
** Positioning
* Objectives
** Marketing objectives
* Strategy
** The Ansoff's matrix
** Website and social media vibrancy
** Entrepreneural and leadership development
** Customer and Supplier Intimacy
* Tatics
** Product
** Price
** Promotion
** Place
** Process
** People
** Programs
* Implementation and Control
** Making Financial Projections 
** Reporting
** Control
